version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    working_dir: /workspace
    volumes:
      - ../:/workspace
    # ports:
    #   - 3000:3000